package com.daily.nexamartpartner.features.admin.category.presentation.viewmodel
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.daily.nexamartpartner.core.result.*
import com.daily.nexamartpartner.features.admin.category.domain.model.*
import com.daily.nexamartpartner.features.admin.category.domain.usecase.*
import com.daily.nexamartpartner.features.admin.category.presentation.state.*
import kotlinx.coroutines.Job
import kotlinx.coroutines.delay
import kotlinx.coroutines.flow.*
import kotlinx.coroutines.launch

sealed interface CategoryEvent { data object SessionExpired:CategoryEvent; data class Message(val text:String):CategoryEvent; data class ActionSucceeded(val action:CategoryAdminAction):CategoryEvent; data object Saved:CategoryEvent }
class CategoryListViewModel(private val getCategories:GetCategoriesUseCase):ViewModel(){
 private val _state=MutableStateFlow(CategoryListUiState()); val uiState:StateFlow<CategoryListUiState> = _state.asStateFlow(); private val _events=MutableSharedFlow<CategoryEvent>(extraBufferCapacity=1); val events=_events.asSharedFlow(); private val items=mutableListOf<Category>(); private var job:Job?=null; private var searchJob:Job?=null; private var page=0; private var hasNext=true
 init{load(0,true)}
 fun search(v:String){_state.update{it.copy(searchQuery=v)};searchJob?.cancel();searchJob=viewModelScope.launch{delay(350);load(0,true)}}
 fun setActive(v:Boolean?){_state.update{it.copy(active=v)};load(0,true)}
 fun clear(){_state.update{it.copy(searchQuery="",active=null)};load(0,true)}
 fun refresh(){if(job?.isActive==true)return;_state.update{it.copy(isRefreshing=true)};load(0,false)}
 fun retry()=load(0,true)
 fun next(){if(!hasNext||job?.isActive==true)return;_state.update{it.copy(isLoadingMore=true)};load(page+1,false,true)}
 private fun load(target:Int,show:Boolean,append:Boolean=false){if(job?.isActive==true){if(append)return;job?.cancel()};if(show)_state.update{it.copy(content=CategoryListUiState.Content.Loading)};job=viewModelScope.launch{val s=_state.value;when(val r=getCategories(CategoryQuery(target,20,s.searchQuery.trim().ifBlank{null},s.active))){is AppResult.Success->{if(!append)items.clear();items.addAll(r.data.categories);page=r.data.page;hasNext=r.data.hasNextPage;_state.update{it.copy(isRefreshing=false,isLoadingMore=false,content=if(items.isEmpty())CategoryListUiState.Content.Empty(if(s.searchQuery.isNotBlank())"No categories match your search." else "No categories found.") else CategoryListUiState.Content.Success(items.toList(),hasNext))}};is AppResult.Failure->{if(r.error.type==FailureType.UNAUTHORIZED)_events.tryEmit(CategoryEvent.SessionExpired);if(append&&items.isNotEmpty()){_events.tryEmit(CategoryEvent.Message(r.error.message));_state.update{it.copy(isLoadingMore=false,isRefreshing=false)} }else _state.update{it.copy(isLoadingMore=false,isRefreshing=false,content=if(r.error.type==FailureType.CONTRACT_MISSING)CategoryListUiState.Content.Unavailable(r.error.message) else CategoryListUiState.Content.Error(r.error.message))}}}}}
}
class CategoryDetailsViewModel(private val id:String,private val get:GetCategoryDetailsUseCase,private val action:PerformCategoryActionUseCase):ViewModel(){private val _state=MutableStateFlow(CategoryDetailsUiState());val uiState=_state.asStateFlow();private val _events=MutableSharedFlow<CategoryEvent>(extraBufferCapacity=1);val events=_events.asSharedFlow();private var job:Job?=null;init{load(true)};fun refresh(){if(job?.isActive==true)return;_state.update{it.copy(isRefreshing=true)};load(false)};fun retry()=load(true);fun perform(a:CategoryAdminAction){if(_state.value.actionInProgress!=null)return;viewModelScope.launch{_state.update{it.copy(actionInProgress=a)};when(val r=action(id,a)){is AppResult.Success->{_events.emit(CategoryEvent.ActionSucceeded(a));load(false)};is AppResult.Failure->{if(r.error.type==FailureType.UNAUTHORIZED)_events.emit(CategoryEvent.SessionExpired) else _events.emit(CategoryEvent.Message(r.error.message));_state.update{it.copy(actionInProgress=null)}}}}};private fun load(show:Boolean){job?.cancel();if(show)_state.update{it.copy(content=CategoryDetailsUiState.Content.Loading)};job=viewModelScope.launch{when(val r=get(id)){is AppResult.Success->_state.update{it.copy(isRefreshing=false,actionInProgress=null,content=CategoryDetailsUiState.Content.Success(r.data))};is AppResult.Failure->{if(r.error.type==FailureType.UNAUTHORIZED)_events.emit(CategoryEvent.SessionExpired);_state.update{it.copy(isRefreshing=false,content=if(r.error.type==FailureType.CONTRACT_MISSING)CategoryDetailsUiState.Content.Unavailable(r.error.message) else CategoryDetailsUiState.Content.Error(r.error.message))}}}}}}
class CategoryFormViewModel(private val id:String?,private val get:GetCategoryDetailsUseCase,private val create:CreateCategoryUseCase,private val update:UpdateCategoryUseCase):ViewModel(){private val _state=MutableStateFlow(CategoryFormUiState(editId=id));val uiState=_state.asStateFlow();private val _events=MutableSharedFlow<CategoryEvent>(extraBufferCapacity=1);val events=_events.asSharedFlow();init{if(!id.isNullOrBlank())load()};private fun load(){viewModelScope.launch{when(val r=get(id!!)){is AppResult.Success->{val c=r.data;_state.update{it.copy(name=c.name,description=c.description.orEmpty(),sortOrder=c.sortOrder?.toString().orEmpty())}};is AppResult.Failure->_state.update{it.copy(error=r.error.message)}}}};fun name(v:String)=_state.update{it.copy(name=v,error=null)};fun description(v:String)=_state.update{it.copy(description=v,error=null)};fun sort(v:String)=_state.update{it.copy(sortOrder=v,error=null)};fun save(){val s=_state.value;if(s.name.trim().isBlank()){_state.update{it.copy(error="Category name is required.")};return};if(s.saving)return;viewModelScope.launch{_state.update{it.copy(saving=true)};val draft=CategoryDraft(s.name.trim(),s.description.trim().ifBlank{null},s.sortOrder.trim().ifBlank{null});val r=if(s.isEdit)update(s.editId!!,draft) else create(draft);when(r){is AppResult.Success->{_state.update{it.copy(saving=false)};_events.emit(CategoryEvent.Saved)};is AppResult.Failure->{if(r.error.type==FailureType.UNAUTHORIZED)_events.emit(CategoryEvent.SessionExpired);_state.update{it.copy(saving=false,error=r.error.message)}}}}}}
