package com.daily.nexamartpartner.features.admin.category.presentation.ui
import android.os.Bundle
import android.view.View
import android.widget.TextView
import androidx.core.view.isVisible
import androidx.core.widget.addTextChangedListener
import androidx.fragment.app.Fragment
import androidx.fragment.app.viewModels
import androidx.lifecycle.Lifecycle
import androidx.lifecycle.lifecycleScope
import androidx.lifecycle.repeatOnLifecycle
import androidx.navigation.fragment.findNavController
import androidx.navigation.fragment.navArgs
import androidx.navigation.navOptions
import androidx.recyclerview.widget.LinearLayoutManager
import com.daily.nexamartpartner.R
import com.daily.nexamartpartner.databinding.*
import com.daily.nexamartpartner.di.appContainer
import com.daily.nexamartpartner.features.admin.category.domain.model.*
import com.daily.nexamartpartner.features.admin.category.presentation.state.*
import com.daily.nexamartpartner.features.admin.category.presentation.viewmodel.*
import com.daily.nexamartpartner.features.auth.presentation.viewmodel.AuthCoordinatorViewModel
import com.daily.nexamartpartner.features.auth.presentation.viewmodel.AuthCoordinatorViewModelFactory
import com.daily.nexamartpartner.core.widgets.UiFeedback
import kotlinx.coroutines.launch
import com.google.android.material.button.MaterialButton

class CategoryListScreen:Fragment(R.layout.fragment_admin_categories){private var _b:FragmentAdminCategoriesBinding?=null;private val b get()=requireNotNull(_b);private val vm:CategoryListViewModel by viewModels{CategoryListViewModelFactory(requireContext().appContainer.provideGetCategoriesUseCase())};private val adapter=CategoryAdapter{findNavController().navigate(R.id.adminCategoryDetailsFragment,Bundle().apply{putString("categoryId",it.categoryId)})};
 override fun onViewCreated(v:View,s:Bundle?){_b=FragmentAdminCategoriesBinding.bind(v);b.categoriesRecyclerView.layoutManager=LinearLayoutManager(requireContext());b.categoriesRecyclerView.adapter=adapter;b.categoriesRecyclerView.addOnScrollListener(object:androidx.recyclerview.widget.RecyclerView.OnScrollListener(){override fun onScrolled(r:androidx.recyclerview.widget.RecyclerView,dx:Int,dy:Int){if(dy>0&&r.layoutManager is LinearLayoutManager){val m=r.layoutManager as LinearLayoutManager;if(m.findLastVisibleItemPosition()>=m.itemCount-3)vm.next()}}});b.categoriesSearchInput.addTextChangedListener{vm.search(it?.toString().orEmpty())};b.categoryActiveAllChip.setOnClickListener{vm.setActive(null)};b.categoryActiveChip.setOnClickListener{vm.setActive(true)};b.categoryActiveInactiveChipSafe()?.setOnClickListener{vm.setActive(false)};b.categoriesSwipeRefresh.setOnRefreshListener{vm.refresh()};b.categoriesRefreshButton.setOnClickListener{vm.refresh()};b.categoriesRetryButton.setOnClickListener{vm.retry()};b.categoriesBackButton.setOnClickListener{findNavController().navigateUp()};b.addCategoryButton.setOnClickListener{findNavController().navigate(R.id.adminCategoryFormFragment)};viewLifecycleOwner.lifecycleScope.launch{viewLifecycleOwner.repeatOnLifecycle(Lifecycle.State.STARTED){vm.events.collect{when(it){CategoryEvent.SessionExpired->findNavController().navigate(R.id.loginFragment);is CategoryEvent.Message->UiFeedback.showSnackbar(b.root,it.text);else->Unit}}}};viewLifecycleOwner.lifecycleScope.launch{viewLifecycleOwner.repeatOnLifecycle(Lifecycle.State.STARTED){vm.uiState.collect(::render)}}}
 private fun render(s:CategoryListUiState){b.categoriesSwipeRefresh.isRefreshing=s.isRefreshing;b.categoriesLoading.isVisible=s.content is CategoryListUiState.Content.Loading;b.categoriesRecyclerView.isVisible=s.content is CategoryListUiState.Content.Success;b.categoriesStateSection.isVisible=s.content !is CategoryListUiState.Content.Success&&!b.categoriesLoading.isVisible;when(val c=s.content){is CategoryListUiState.Content.Success->{adapter.submitList(c.items);b.categoriesStateTitle.text="Categories";b.categoriesStateMessage.text="";b.categoriesRetryButton.isVisible=false};is CategoryListUiState.Content.Empty->{b.categoriesStateTitle.text="No categories";b.categoriesStateMessage.text=c.message;b.categoriesRetryButton.isVisible=false};is CategoryListUiState.Content.Error->{b.categoriesStateTitle.text="Unable to load categories";b.categoriesStateMessage.text=c.message;b.categoriesRetryButton.isVisible=true};is CategoryListUiState.Content.Unavailable->{b.categoriesStateTitle.text="Category API unavailable";b.categoriesStateMessage.text=c.message;b.categoriesRetryButton.isVisible=false};else->Unit}}
 private fun FragmentAdminCategoriesBinding.categoryActiveInactiveChipSafe()=categoryInactiveChip
 override fun onDestroyView(){b.categoriesRecyclerView.adapter=null;_b=null;super.onDestroyView()}}

class CategoryDetailsScreen:Fragment(R.layout.fragment_admin_category_details){private var _b:FragmentAdminCategoryDetailsBinding?=null;private val b get()=requireNotNull(_b);private val id by lazy{requireArguments().getString("categoryId").orEmpty()};private val vm:CategoryDetailsViewModel by viewModels{CategoryDetailsViewModelFactory(id,requireContext().appContainer.provideGetCategoryDetailsUseCase(),requireContext().appContainer.providePerformCategoryActionUseCase())};override fun onViewCreated(v:View,s:Bundle?){_b=FragmentAdminCategoryDetailsBinding.bind(v);b.categoryDetailsBackButton.setOnClickListener{findNavController().navigateUp()};b.categoryDetailsRefreshButton.setOnClickListener{vm.refresh()};b.categoryDetailsRetryButton.setOnClickListener{vm.retry()};viewLifecycleOwner.lifecycleScope.launch{viewLifecycleOwner.repeatOnLifecycle(Lifecycle.State.STARTED){vm.events.collect{e->when(e){CategoryEvent.SessionExpired->findNavController().navigate(R.id.loginFragment);is CategoryEvent.Message->UiFeedback.showSnackbar(b.root,e.text);is CategoryEvent.ActionSucceeded->{if(e.action==CategoryAdminAction.DELETE)findNavController().navigateUp()};else->Unit}}}};viewLifecycleOwner.lifecycleScope.launch{viewLifecycleOwner.repeatOnLifecycle(Lifecycle.State.STARTED){vm.uiState.collect(::render)}}}
private fun render(s:CategoryDetailsUiState){b.categoryDetailsLoading.isVisible=s.content is CategoryDetailsUiState.Content.Loading;b.categoryDetailsStateSection.isVisible=s.content is CategoryDetailsUiState.Content.Error||s.content is CategoryDetailsUiState.Content.Unavailable;b.categoryDetailsContent.isVisible=s.content is CategoryDetailsUiState.Content.Success;when(val c=s.content){is CategoryDetailsUiState.Content.Success->{val x=c.category;b.categoryDetailsName.text=x.name;b.categoryDetailsDescription.text=x.description.orEmpty();b.categoryDetailsMeta.text=buildString{append(if(x.active==true)"Active" else if(x.active==false)"Inactive" else "Status unavailable");x.productCount?.let{append("\nProducts: ").append(it)};x.sortOrder?.let{append("\nDisplay order: ").append(it)};x.createdAt?.let{append("\nCreated: ").append(it)}};b.categoryDetailsActions.removeAllViews();x.allowedActions.forEach{a->b.categoryDetailsActions.addView(MaterialButton(requireContext()).apply{text=a.backendValue;setOnClickListener{if(a==CategoryAdminAction.EDIT){findNavController().navigate(R.id.adminCategoryFormFragment,Bundle().apply{putString("categoryId",x.categoryId)})}else UiFeedback.showConfirmationDialog(b.root,a.backendValue,"Confirm ${a.backendValue.lowercase()} for ${x.name}?",getString(R.string.common_confirm),getString(R.string.common_cancel)){vm.perform(a)}}})}};is CategoryDetailsUiState.Content.Error->{b.categoryDetailsStateTitle.text="Unable to load category";b.categoryDetailsStateMessage.text=c.message};is CategoryDetailsUiState.Content.Unavailable->{b.categoryDetailsStateTitle.text="Category API unavailable";b.categoryDetailsStateMessage.text=c.message};else->Unit}}
override fun onDestroyView(){_b=null;super.onDestroyView()}}

class CategoryFormScreen:Fragment(R.layout.fragment_admin_category_form){private var _b:FragmentAdminCategoryFormBinding?=null;private val b get()=requireNotNull(_b);private val vm:CategoryFormViewModel by viewModels{CategoryFormViewModelFactory(requireArguments().getString("categoryId"),requireContext().appContainer.provideGetCategoryDetailsUseCase(),requireContext().appContainer.provideCreateCategoryUseCase(),requireContext().appContainer.provideUpdateCategoryUseCase())};override fun onViewCreated(v:View,s:Bundle?){_b=FragmentAdminCategoryFormBinding.bind(v);b.categoryFormTitle.text=if(vm.uiState.value.isEdit)"Edit Category" else "Add Category";b.categoryNameInput.addTextChangedListener{vm.name(it?.toString().orEmpty())};b.categoryDescriptionInput.addTextChangedListener{vm.description(it?.toString().orEmpty())};b.categorySortOrderInput.addTextChangedListener{vm.sort(it?.toString().orEmpty())};b.categoryCancelButton.setOnClickListener{findNavController().navigateUp()};b.categorySaveButton.setOnClickListener{vm.save()};viewLifecycleOwner.lifecycleScope.launch{viewLifecycleOwner.repeatOnLifecycle(Lifecycle.State.STARTED){vm.events.collect{e->when(e){CategoryEvent.Saved->findNavController().navigateUp();CategoryEvent.SessionExpired->findNavController().navigate(R.id.loginFragment);else->Unit}}}};viewLifecycleOwner.lifecycleScope.launch{viewLifecycleOwner.repeatOnLifecycle(Lifecycle.State.STARTED){vm.uiState.collect{st->b.categorySaveButton.isEnabled=!st.saving;b.categoryFormError.text=st.error.orEmpty();if(st.name!=b.categoryNameInput.text?.toString())b.categoryNameInput.setText(st.name);if(st.description!=b.categoryDescriptionInput.text?.toString())b.categoryDescriptionInput.setText(st.description);if(st.sortOrder!=b.categorySortOrderInput.text?.toString())b.categorySortOrderInput.setText(st.sortOrder)}}}}
override fun onDestroyView(){_b=null;super.onDestroyView()}}
