ALTER TABLE user_accounts ADD COLUMN delivery_partner_id BIGINT NULL;
ALTER TABLE user_accounts ADD KEY idx_user_accounts_delivery_partner (delivery_partner_id);
ALTER TABLE delivery_partners ADD COLUMN email VARCHAR(160) NULL;
ALTER TABLE delivery_partners ADD COLUMN vehicle_type VARCHAR(40) NULL;
ALTER TABLE delivery_partners ADD COLUMN license_reference VARCHAR(120) NULL;
ALTER TABLE delivery_partners ADD COLUMN verification_status VARCHAR(30) NOT NULL DEFAULT 'VERIFIED';
ALTER TABLE delivery_partners ADD COLUMN available BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE delivery_partners ADD COLUMN last_active_at DATETIME NULL;
ALTER TABLE customers ADD COLUMN status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE customers ADD COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE user_accounts ADD CONSTRAINT fk_user_accounts_delivery_partner FOREIGN KEY (delivery_partner_id) REFERENCES delivery_partners(id) ON DELETE SET NULL;
CREATE UNIQUE INDEX uk_delivery_partners_email ON delivery_partners(email);
