package com.zeptopluse.entity;

public enum OrderStatus {
    CREATED,
    PAYMENT_PENDING,
    PARTNER_SEARCHING,
    PARTNER_ASSIGNED,
    PARTNER_ACCEPTED,
    PICKING,
    PACKED,
    DELIVERY_SEARCHING,
    DELIVERY_ASSIGNED,
    PICKED_UP,
    OUT_FOR_DELIVERY,
    DELIVERED,
    CANCELLED,
    OUT_OF_STOCK,
    DELIVERY_FAILED,
    RETURN_REQUESTED,
    RETURNED
}