package com.zeptopluse.controller;

import com.zeptopluse.auth.UserAccount;
import com.zeptopluse.auth.UserAccountRepository;
import com.zeptopluse.entity.*;
import com.zeptopluse.exception.ConflictException;
import com.zeptopluse.exception.ResourceNotFoundException;
import com.zeptopluse.repository.*;
import jakarta.transaction.Transactional;
import lombok.RequiredArgsConstructor;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;

import java.math.BigDecimal;
import java.time.*;
import java.util.*;
import java.util.stream.Collectors;

@RestController
@RequestMapping("/api/v1")
@RequiredArgsConstructor
public class AdminOperationsController {
    private final OrderRepository orders;
    private final CustomerRepository customers;
    private final ProductRepository products;
    private final CategoryRepository categories;
    private final DeliveryPartnerRepository partners;
    private final OrderAssignmentRepository assignments;
    private final UserAccountRepository users;

    @GetMapping("/admin/dashboard") @PreAuthorize("hasRole('ADMIN')")
    public Map<String,Object> dashboard() {
        List<CustomerOrder> all = orders.findAllByOrderByCreatedAtDesc(); LocalDate today=LocalDate.now();
        long todayOrders=all.stream().filter(o->o.getCreatedAt()!=null&&o.getCreatedAt().toLocalDate().equals(today)).count();
        long pending=all.stream().filter(o->EnumSet.of(OrderStatus.CREATED,OrderStatus.PAYMENT_PENDING,OrderStatus.PARTNER_SEARCHING,OrderStatus.PARTNER_ASSIGNED,OrderStatus.PARTNER_ACCEPTED,OrderStatus.PICKING,OrderStatus.PACKED,OrderStatus.DELIVERY_SEARCHING,OrderStatus.DELIVERY_ASSIGNED).contains(o.getStatus())).count();
        long out=all.stream().filter(o->o.getStatus()==OrderStatus.OUT_FOR_DELIVERY).count();
        long deliveredToday=all.stream().filter(o->o.getStatus()==OrderStatus.DELIVERED&&o.getUpdatedAt()!=null&&o.getUpdatedAt().toLocalDate().equals(today)).count();
        BigDecimal sales=all.stream().filter(o->o.getCreatedAt()!=null&&o.getCreatedAt().toLocalDate().equals(today)&&o.getStatus()!=OrderStatus.CANCELLED).map(CustomerOrder::getTotalAmount).filter(Objects::nonNull).reduce(BigDecimal.ZERO,BigDecimal::add);
        List<Map<String,Object>> recent=all.stream().limit(10).map(this::recentOrder).toList();
        return Map.of("totalOrders",(long)all.size(),"todayOrders",todayOrders,"pendingOrders",pending,"outForDelivery",out,"deliveredToday",deliveredToday,"todaySales",sales,"currencyCode","INR","recentOrders",recent);
    }

    @GetMapping("/admin/orders") @PreAuthorize("hasRole('ADMIN')")
    public Map<String,Object> adminOrders(@RequestParam(defaultValue="0") int page,@RequestParam(defaultValue="20") int pageSize,@RequestParam(required=false) String searchText,@RequestParam(required=false) String status,@RequestParam(required=false) String paymentStatus,@RequestParam(required=false) String sort){
        List<CustomerOrder> list=orders.findAllByOrderByCreatedAtDesc();
        if(searchText!=null&&!searchText.isBlank()){String q=searchText.toLowerCase(); list=list.stream().filter(o->o.getOrderNumber().toLowerCase().contains(q)||o.getCustomer().getName().toLowerCase().contains(q)||o.getCustomer().getPhone().contains(q)).toList();}
        if(status!=null&&!status.isBlank()) try{OrderStatus st=OrderStatus.valueOf(status.toUpperCase()); list=list.stream().filter(o->o.getStatus()==st).toList();}catch(Exception ignored){}
        if(paymentStatus!=null&&!paymentStatus.isBlank()) try{PaymentStatus st=PaymentStatus.valueOf(paymentStatus.toUpperCase()); list=list.stream().filter(o->o.getPaymentStatus()==st).toList();}catch(Exception ignored){}
        if("AMOUNT_HIGH_TO_LOW".equalsIgnoreCase(sort)) list=list.stream().sorted(Comparator.comparing(CustomerOrder::getTotalAmount,Comparator.nullsLast(Comparator.reverseOrder()))).toList();
        else if("AMOUNT_LOW_TO_HIGH".equalsIgnoreCase(sort)) list=list.stream().sorted(Comparator.comparing(CustomerOrder::getTotalAmount,Comparator.nullsLast(Comparator.naturalOrder()))).toList();
        else if("OLDEST".equalsIgnoreCase(sort)) list=list.stream().sorted(Comparator.comparing(CustomerOrder::getCreatedAt)).toList();
        return page(list,page,pageSize,this::adminOrderSummary);
    }

    @GetMapping("/admin/orders/{id}") @PreAuthorize("hasRole('ADMIN')") public Map<String,Object> adminOrder(@PathVariable Long id){return adminOrderDetails(order(id));}
    @PatchMapping("/admin/orders/{id}/status") @PreAuthorize("hasRole('ADMIN')") @Transactional public void updateStatus(@PathVariable Long id,@RequestBody Map<String,String> body){ CustomerOrder o=order(id); OrderStatus next=parseStatus(body.get("status")); validateTransition(o.getStatus(),next); o.setStatus(next); if(next==OrderStatus.DELIVERY_ASSIGNED && assignments.findByOrderId(id).isEmpty()){ DeliveryPartner eligible=partners.findAllByOrderByCreatedAtDesc().stream().filter(x->x.isActive()&&x.isAvailable()&&"VERIFIED".equalsIgnoreCase(x.getVerificationStatus())).findFirst().orElseThrow(()->new ConflictException("No available delivery partner is currently eligible")); OrderAssignment a=new OrderAssignment(); a.setOrder(o); a.setDeliveryPartner(eligible); a.setStatus("ASSIGNED"); assignments.save(a); } }
    @PostMapping("/admin/orders/{id}/cancel") @PreAuthorize("hasRole('ADMIN')") @Transactional public void cancelAdmin(@PathVariable Long id,@RequestBody(required=false) Map<String,String> body){cancelOrder(order(id));}

    @GetMapping("/admin/categories") @PreAuthorize("hasRole('ADMIN')") public Map<String,Object> categories(@RequestParam(defaultValue="0") int page,@RequestParam(defaultValue="50") int pageSize,@RequestParam(required=false) String search,@RequestParam(required=false) Boolean active){ List<Category> list=categories.findAll(); if(search!=null&&!search.isBlank()){String q=search.toLowerCase();list=list.stream().filter(c->c.getName().toLowerCase().contains(q)).toList();} if(active!=null) list=list.stream().filter(c->c.isActive()==active).toList(); list=list.stream().sorted(Comparator.comparingInt(Category::getDisplayOrder)).toList(); return page(list,page,pageSize,this::categoryDto); }
    @GetMapping("/admin/categories/{id}") @PreAuthorize("hasRole('ADMIN')") public Map<String,Object> category(@PathVariable Long id){return categoryDto(cat(id));}
    @PostMapping("/admin/categories") @PreAuthorize("hasRole('ADMIN')") @Transactional public Map<String,Object> createCategory(@RequestBody Map<String,String> b){ Category c=new Category(); c.setName(req(b,"name")); c.setSlug(slug(c.getName())); c.setDescription(b.get("description")); c.setDisplayOrder(intValue(b.get("sortOrder"),0)); c.setActive(true); return categoryDto(categories.save(c)); }
    @PatchMapping("/admin/categories/{id}") @PreAuthorize("hasRole('ADMIN')") @Transactional public Map<String,Object> updateCategory(@PathVariable Long id,@RequestBody Map<String,String> b){Category c=cat(id); if(b.containsKey("name")){c.setName(req(b,"name"));c.setSlug(slug(c.getName()));} c.setDescription(b.get("description")); if(b.containsKey("sortOrder"))c.setDisplayOrder(intValue(b.get("sortOrder"),c.getDisplayOrder())); return categoryDto(c);}
    @PatchMapping("/admin/categories/{id}/action") @PreAuthorize("hasRole('ADMIN')") @Transactional public void categoryAction(@PathVariable Long id,@RequestBody Map<String,String> b){Category c=cat(id);String a=b.getOrDefault("action","").toUpperCase();if("ACTIVATE".equals(a))c.setActive(true);else if("DEACTIVATE".equals(a)||"DELETE".equals(a))c.setActive(false);else if(!"EDIT".equals(a))throw new IllegalArgumentException("Unsupported category action");}

    @GetMapping("/admin/products") @PreAuthorize("hasRole('ADMIN')") public Map<String,Object> adminProducts(@RequestParam(defaultValue="0") int page,@RequestParam(defaultValue="20") int pageSize,@RequestParam(required=false) String searchText,@RequestParam(required=false) String categoryId,@RequestParam(required=false) String status,@RequestParam(required=false) String sort){List<Product> list=products.findAll(); if(searchText!=null&&!searchText.isBlank()){String q=searchText.toLowerCase();list=list.stream().filter(p->p.getName().toLowerCase().contains(q)||p.getSku().toLowerCase().contains(q)).toList();}if(categoryId!=null&&!categoryId.isBlank())list=list.stream().filter(p->p.getCategory().getId().toString().equals(categoryId)).toList();if("ACTIVE".equalsIgnoreCase(status))list=list.stream().filter(Product::isAvailability).toList();if("INACTIVE".equalsIgnoreCase(status)||"DISABLED".equalsIgnoreCase(status))list=list.stream().filter(p->!p.isAvailability()).toList();Comparator<Product> cmp=Comparator.comparing(Product::getName,String.CASE_INSENSITIVE_ORDER);if("NEWEST".equalsIgnoreCase(sort))cmp=Comparator.comparing(Product::getCreatedAt,Comparator.nullsLast(Comparator.reverseOrder()));else if("PRICE_LOW_TO_HIGH".equalsIgnoreCase(sort))cmp=Comparator.comparing(Product::getSellingPrice);else if("PRICE_HIGH_TO_LOW".equalsIgnoreCase(sort))cmp=Comparator.comparing(Product::getSellingPrice).reversed();list=list.stream().sorted(cmp).toList();return page(list,page,pageSize,this::productSummary);}
    @GetMapping("/admin/products/{id}") @PreAuthorize("hasRole('ADMIN')") public Map<String,Object> adminProduct(@PathVariable Long id){return productDetails(product(id));}
    @GetMapping("/admin/products/category-options") @PreAuthorize("hasRole('ADMIN')") public List<Map<String,Object>> categoryOptions(){return categories.findAll().stream().filter(Category::isActive).sorted(Comparator.comparingInt(Category::getDisplayOrder)).map(c->Map.<String,Object>of("categoryId",c.getId().toString(),"name",c.getName())).toList();}
    @PostMapping("/admin/products") @PreAuthorize("hasRole('ADMIN')") @Transactional public Map<String,Object> createProduct(@RequestBody Map<String,String>b){Product p=new Product();fillProduct(p,b);return productDetails(products.save(p));}
    @PatchMapping("/admin/products/{id}") @PreAuthorize("hasRole('ADMIN')") @Transactional public Map<String,Object> updateProduct(@PathVariable Long id,@RequestBody Map<String,String>b){Product p=product(id);fillProduct(p,b);return productDetails(p);}
    @PatchMapping("/admin/products/{id}/action") @PreAuthorize("hasRole('ADMIN')") @Transactional public void productAction(@PathVariable Long id,@RequestBody Map<String,String>b){Product p=product(id);String a=b.getOrDefault("action","").toUpperCase();if("ACTIVATE".equals(a))p.setAvailability(true);else if("DEACTIVATE".equals(a)||"DELETE".equals(a))p.setAvailability(false);else if(!"EDIT".equals(a))throw new IllegalArgumentException("Unsupported product action");}

    @GetMapping("/admin/customers") @PreAuthorize("hasRole('ADMIN')") public Map<String,Object> adminCustomers(@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int pageSize,@RequestParam(required=false)String search,@RequestParam(required=false)String status){List<Customer> list=customers.findAllByOrderByCreatedAtDesc();if(search!=null&&!search.isBlank()){String q=search.toLowerCase();list=list.stream().filter(c->c.getName().toLowerCase().contains(q)||(c.getEmail()!=null&&c.getEmail().toLowerCase().contains(q))||c.getPhone().contains(q)).toList();}if(status!=null&&!status.isBlank())list=list.stream().filter(c->c.getStatus().equalsIgnoreCase(status)).toList();return page(list,page,pageSize,this::customerDto);}
    @GetMapping("/admin/customers/{id}") @PreAuthorize("hasRole('ADMIN')") public Map<String,Object> adminCustomer(@PathVariable Long id){return customerDto(customer(id));}
    @PatchMapping("/admin/customers/{id}/action") @PreAuthorize("hasRole('ADMIN')") @Transactional public void customerAction(@PathVariable Long id,@RequestBody Map<String,String>b){Customer c=customer(id);String a=b.getOrDefault("action","").toUpperCase();switch(a){case "ACTIVATE","REACTIVATE"->c.setStatus("ACTIVE");case "DEACTIVATE"->c.setStatus("INACTIVE");case "SUSPEND"->c.setStatus("SUSPENDED");default->throw new IllegalArgumentException("Unsupported customer action");}}

    @GetMapping("/admin/delivery-partners") @PreAuthorize("hasRole('ADMIN')") public Map<String,Object> adminPartners(@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int pageSize,@RequestParam(required=false)String searchText,@RequestParam(required=false)String accountStatus,@RequestParam(required=false)String verificationStatus,@RequestParam(required=false)String availability){List<DeliveryPartner> list=partners.findAllByOrderByCreatedAtDesc();if(searchText!=null&&!searchText.isBlank()){String q=searchText.toLowerCase();list=list.stream().filter(p->p.getName().toLowerCase().contains(q)||(p.getPhone()!=null&&p.getPhone().contains(q))||(p.getEmail()!=null&&p.getEmail().toLowerCase().contains(q))).toList();}if(accountStatus!=null&&!accountStatus.isBlank())list=list.stream().filter(p->("ACTIVE".equalsIgnoreCase(accountStatus)?p.isActive():!p.isActive())).toList();if(verificationStatus!=null&&!verificationStatus.isBlank())list=list.stream().filter(p->p.getVerificationStatus().equalsIgnoreCase(verificationStatus)).toList();if(availability!=null&&!availability.isBlank())list=list.stream().filter(p->("ONLINE".equalsIgnoreCase(availability)?p.isAvailable():!p.isAvailable())).toList();return page(list,page,pageSize,this::partnerSummary);}
    @GetMapping("/admin/delivery-partners/{id}") @PreAuthorize("hasRole('ADMIN')") public Map<String,Object> adminPartner(@PathVariable Long id){return partnerDetails(partner(id));}
    @PatchMapping("/admin/delivery-partners/{id}/action") @PreAuthorize("hasRole('ADMIN')") @Transactional public void partnerAction(@PathVariable Long id,@RequestBody Map<String,String>b){DeliveryPartner p=partner(id);String a=b.getOrDefault("action","").toUpperCase();switch(a){case "VERIFY"->p.setVerificationStatus("VERIFIED");case "REJECT"->p.setVerificationStatus("REJECTED");case "ACTIVATE","REACTIVATE"->p.setActive(true);case "DEACTIVATE","SUSPEND"->p.setActive(false);default->throw new IllegalArgumentException("Unsupported partner action");}}

    @GetMapping("/delivery/dashboard") @PreAuthorize("hasRole('DELIVERY_PARTNER')") public Map<String,Object> deliveryDashboard(java.security.Principal principal){DeliveryPartner p=currentPartner(principal);List<OrderAssignment>a=assignments.findByDeliveryPartnerIdOrderByAssignedAtDesc(p.getId());long completed=a.stream().filter(x->x.getOrder().getStatus()==OrderStatus.DELIVERED).count();long active=a.stream().filter(x->x.getOrder().getStatus()!=OrderStatus.DELIVERED&&x.getOrder().getStatus()!=OrderStatus.CANCELLED).count();BigDecimal earnings=BigDecimal.ZERO;List<Map<String,Object>> recent=a.stream().limit(10).map(x->Map.<String,Object>of("orderId",x.getOrder().getId().toString(),"status",x.getOrder().getStatus().name(),"customerName",x.getOrder().getCustomer().getName(),"createdAt",x.getOrder().getCreatedAt(),"amount",decimal(x.getOrder().getTotalAmount()))).toList();return Map.of("activeOrders",active,"assignedOrders",a.size(),"pickedUpOrders",a.stream().filter(x->x.getOrder().getStatus()==OrderStatus.PICKED_UP).count(),"outForDeliveryOrders",a.stream().filter(x->x.getOrder().getStatus()==OrderStatus.OUT_FOR_DELIVERY).count(),"completedToday",completed,"todayEarnings",decimal(earnings),"currencyCode","INR","availability",p.isAvailable()?"ONLINE":"OFFLINE","recentOrders",recent);}

    @GetMapping("/delivery/orders") @PreAuthorize("hasRole('DELIVERY_PARTNER')") public Map<String,Object> deliveryOrders(java.security.Principal principal,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int pageSize,@RequestParam(required=false)String searchText,@RequestParam(required=false)String status,@RequestParam(required=false)String fromDate,@RequestParam(required=false)String toDate){DeliveryPartner p=currentPartner(principal);List<OrderAssignment> as=assignments.findByDeliveryPartnerIdOrderByAssignedAtDesc(p.getId());List<CustomerOrder> list=as.stream().map(OrderAssignment::getOrder).filter(o->status==null||status.isBlank()||o.getStatus().name().equalsIgnoreCase(status)).filter(o->searchText==null||searchText.isBlank()||o.getOrderNumber().toLowerCase().contains(searchText.toLowerCase())||o.getCustomer().getName().toLowerCase().contains(searchText.toLowerCase())).toList();return page(list,page,pageSize,this::deliverySummary);}
    @GetMapping("/delivery/orders/{id}") @PreAuthorize("hasRole('DELIVERY_PARTNER')") public Map<String,Object> deliveryOrder(@PathVariable Long id,java.security.Principal principal){DeliveryPartner p=currentPartner(principal);OrderAssignment a=assignments.findByOrderId(id).orElseThrow(()->new ResourceNotFoundException("Delivery assignment not found"));if(!a.getDeliveryPartner().getId().equals(p.getId()))throw new ResourceNotFoundException("Delivery order not found");return deliveryDetails(a.getOrder(),a);}
    @PatchMapping("/delivery/orders/{id}/action") @PreAuthorize("hasRole('DELIVERY_PARTNER')") @Transactional public void deliveryAction(@PathVariable Long id,java.security.Principal principal,@RequestBody Map<String,String>b){DeliveryPartner p=currentPartner(principal);OrderAssignment a=assignments.findByOrderId(id).orElseThrow(()->new ResourceNotFoundException("Delivery assignment not found"));if(!a.getDeliveryPartner().getId().equals(p.getId()))throw new ResourceNotFoundException("Delivery order not found");String action=b.getOrDefault("action","").toUpperCase();CustomerOrder o=a.getOrder();switch(action){case "ACCEPT"-> {if(o.getStatus()!=OrderStatus.DELIVERY_ASSIGNED&&o.getStatus()!=OrderStatus.PARTNER_ASSIGNED)throw new ConflictException("Order cannot be accepted");o.setStatus(OrderStatus.PARTNER_ACCEPTED);a.setStatus("ACCEPTED");}case "PICKUP"->{if(o.getStatus()!=OrderStatus.PARTNER_ACCEPTED&&o.getStatus()!=OrderStatus.PACKED)throw new ConflictException("Order cannot be picked up");o.setStatus(OrderStatus.PICKED_UP);a.setStatus("PICKED_UP");}case "OUT_FOR_DELIVERY"->{if(o.getStatus()!=OrderStatus.PICKED_UP)throw new ConflictException("Order is not picked up");o.setStatus(OrderStatus.OUT_FOR_DELIVERY);a.setStatus("OUT_FOR_DELIVERY");}case "COMPLETE"->{if(o.getStatus()!=OrderStatus.OUT_FOR_DELIVERY)throw new ConflictException("Order is not out for delivery");o.setStatus(OrderStatus.DELIVERED);a.setStatus("DELIVERED");a.setDeliveredAt(LocalDateTime.now());}case "REJECT","CANCEL"->{if(o.getStatus()==OrderStatus.DELIVERED)throw new ConflictException("Delivered order cannot be cancelled");o.setStatus(OrderStatus.CANCELLED);a.setStatus("CANCELLED");}default->throw new IllegalArgumentException("Unsupported delivery action");}}

    @GetMapping("/delivery/availability") @PreAuthorize("hasRole('DELIVERY_PARTNER')") public Map<String,Object> availability(java.security.Principal principal){DeliveryPartner p=currentPartner(principal);Map<String,Object> m=new LinkedHashMap<>();m.put("available",p.isAvailable());m.put("status",p.isAvailable()?"ONLINE":"OFFLINE");m.put("canChange",true);m.put("reason",null);m.put("updatedAt",p.getLastActiveAt());return m;}
    @PutMapping("/delivery/availability") @PreAuthorize("hasRole('DELIVERY_PARTNER')") @Transactional public Map<String,Object> updateAvailability(java.security.Principal principal,@RequestBody Map<String,Object>b){DeliveryPartner p=currentPartner(principal);boolean v=Boolean.parseBoolean(String.valueOf(b.getOrDefault("available",false)));p.setAvailable(v);p.setLastActiveAt(LocalDateTime.now());return availability(principal);}
    @GetMapping("/delivery/profile") @PreAuthorize("hasRole('DELIVERY_PARTNER')") public Map<String,Object> profile(java.security.Principal principal){return profileDto(currentPartner(principal));}
    @PutMapping("/delivery/profile") @PreAuthorize("hasRole('DELIVERY_PARTNER')") @Transactional public Map<String,Object> updateProfile(java.security.Principal principal,@RequestBody Map<String,Object>b){DeliveryPartner p=currentPartner(principal);if(b.get("name")!=null)p.setName(String.valueOf(b.get("name")));if(b.get("email")!=null)p.setEmail(String.valueOf(b.get("email")));if(b.get("vehicleType")!=null)p.setVehicleType(String.valueOf(b.get("vehicleType")));if(b.get("vehicleNumber")!=null)p.setVehicleNumber(String.valueOf(b.get("vehicleNumber")));if(b.get("licenseReference")!=null)p.setLicenseReference(String.valueOf(b.get("licenseReference")));return profileDto(p);}
    @GetMapping("/delivery/earnings/summary") @PreAuthorize("hasRole('DELIVERY_PARTNER')") public Map<String,Object> earningsSummary(java.security.Principal principal){return Map.of("currencyCode","INR","today",decimal(BigDecimal.ZERO),"thisWeek",decimal(BigDecimal.ZERO),"thisMonth",decimal(BigDecimal.ZERO),"completedDeliveries",assignments.findByDeliveryPartnerIdOrderByAssignedAtDesc(currentPartner(principal).getId()).stream().filter(a->a.getOrder().getStatus()==OrderStatus.DELIVERED).count(),"pendingPayout",decimal(BigDecimal.ZERO),"totalEarned",decimal(BigDecimal.ZERO));}
    @GetMapping("/delivery/earnings/history") @PreAuthorize("hasRole('DELIVERY_PARTNER')") public Map<String,Object> earningsHistory(){return Map.of("content",List.of(),"number",0,"size",20,"totalPages",0,"totalElements",0,"last",true);}
    @GetMapping("/delivery/notifications") @PreAuthorize("hasRole('DELIVERY_PARTNER')") public Map<String,Object> notifications(@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int pageSize){return Map.of("items",List.of(),"page",page,"pageSize",pageSize,"totalPages",0,"totalElements",0,"hasNextPage",false,"unreadCount",0);}
    @PostMapping("/delivery/notifications/{id}/read") @PreAuthorize("hasRole('DELIVERY_PARTNER')") public void readNotification(@PathVariable String id){}
    @PostMapping("/delivery/notifications/read-all") @PreAuthorize("hasRole('DELIVERY_PARTNER')") public void readAllNotifications(){}

    private DeliveryPartner currentPartner(java.security.Principal principal){UserAccount u=users.findByEmailIgnoreCase(principal.getName()).orElseGet(()->users.findById(Long.valueOf(principal.getName())).orElseThrow());if(u.getDeliveryPartnerId()==null)throw new ResourceNotFoundException("Delivery partner profile not found");return partner(u.getDeliveryPartnerId());}
    private CustomerOrder order(Long id){return orders.findById(id).orElseThrow(()->new ResourceNotFoundException("Order not found: "+id));}
    private Product product(Long id){return products.findById(id).orElseThrow(()->new ResourceNotFoundException("Product not found: "+id));}
    private Category cat(Long id){return categories.findById(id).orElseThrow(()->new ResourceNotFoundException("Category not found: "+id));}
    private Customer customer(Long id){return customers.findById(id).orElseThrow(()->new ResourceNotFoundException("Customer not found: "+id));}
    private DeliveryPartner partner(Long id){return partners.findById(id).orElseThrow(()->new ResourceNotFoundException("Delivery partner not found: "+id));}
    private OrderStatus parseStatus(String s){try{return OrderStatus.valueOf(s.trim().toUpperCase());}catch(Exception e){throw new IllegalArgumentException("Unsupported order status");}}
    private void validateTransition(OrderStatus cur,OrderStatus next){if(cur==OrderStatus.DELIVERED||cur==OrderStatus.CANCELLED)throw new ConflictException("Finalized order cannot change status");}
    private void cancelOrder(CustomerOrder o){if(EnumSet.of(OrderStatus.DELIVERED,OrderStatus.OUT_FOR_DELIVERY,PICKED_UP_SAFE()).contains(o.getStatus()))throw new ConflictException("This order can no longer be cancelled");o.setStatus(OrderStatus.CANCELLED);}
    private OrderStatus PICKED_UP_SAFE(){return OrderStatus.PICKED_UP;}
    private String req(Map<String,String>b,String k){String v=b.get(k);if(v==null||v.isBlank())throw new IllegalArgumentException(k+" is required");return v.trim();}
    private int intValue(String v,int d){try{return v==null?d:Integer.parseInt(v);}catch(Exception e){return d;}}
    private String slug(String s){return s.toLowerCase(Locale.ROOT).trim().replaceAll("[^a-z0-9]+","-").replaceAll("^-|-$","");}
    private void fillProduct(Product p,Map<String,String>b){if(b.get("name")!=null)p.setName(req(b,"name"));if(b.get("description")!=null)p.setDescription(b.get("description"));if(b.get("sku")!=null&&!b.get("sku").isBlank())p.setSku(b.get("sku"));else if(p.getSku()==null)p.setSku("NM-"+UUID.randomUUID().toString().substring(0,8).toUpperCase());if(b.get("categoryId")!=null)p.setCategory(cat(Long.valueOf(b.get("categoryId"))));if(p.getCategory()==null)throw new IllegalArgumentException("categoryId is required");if(b.get("price")!=null){BigDecimal price=new BigDecimal(b.get("price"));p.setMrp(price);p.setSellingPrice(price);}else if(p.getSellingPrice()==null)p.setSellingPrice(BigDecimal.ZERO);if(p.getMrp()==null)p.setMrp(p.getSellingPrice());p.setDiscountPercentage(b.get("discountPercent")==null?BigDecimal.ZERO:new BigDecimal(b.get("discountPercent")));p.setStockQuantity(intValue(b.get("stock"),p.getStockQuantity()));p.setUnit(b.getOrDefault("unit",p.getUnit()==null?"unit":p.getUnit()));p.setAvailability(true);}
    private Map<String,Object> recentOrder(CustomerOrder o){return Map.of("orderId",o.getId().toString(),"customerName",o.getCustomer().getName(),"amount",o.getTotalAmount().doubleValue(),"status",o.getStatus().name(),"createdAt",o.getCreatedAt());}
    private Map<String,Object> adminOrderSummary(CustomerOrder o){return Map.of("orderId",o.getId().toString(),"customerName",o.getCustomer().getName(),"customerPhone",o.getCustomer().getPhone(),"itemCount",o.getItems().size(),"totalAmount",decimal(o.getTotalAmount()),"currencyCode","INR","status",adminStatus(o.getStatus()),"paymentStatus",o.getPaymentStatus().name(),"deliveryStatus",assignmentStatus(o),"createdAt",o.getCreatedAt());}
    private Map<String,Object> adminOrderDetails(CustomerOrder o){OrderAssignment a=assignments.findByOrderId(o.getId()).orElse(null);Map<String,Object>m=new LinkedHashMap<>();m.put("orderId",o.getId().toString());m.put("createdAt",o.getCreatedAt());m.put("status",adminStatus(o.getStatus()));m.put("customer",Map.of("name",o.getCustomer().getName(),"phone",o.getCustomer().getPhone(),"address",o.getAddressSnapshot()));m.put("items",o.getItems().stream().map(i->Map.of("productName",i.getProductName(),"quantity",i.getQuantity(),"unitPrice",decimal(i.getUnitPrice()),"lineTotal",decimal(i.getLineTotal()))).toList());m.put("payment",Map.of("method",o.getPaymentMethod().name(),"status",o.getPaymentStatus().name(),"transactionReference",""));m.put("totals",Map.of("subtotal",decimal(o.getSubtotal()),"deliveryFee",decimal(o.getDeliveryFee()),"discount",decimal(o.getDiscountAmount()),"tax",decimal(BigDecimal.ZERO),"grandTotal",decimal(o.getTotalAmount()),"currencyCode","INR"));Map<String,Object>d=new LinkedHashMap<>();d.put("status",assignmentStatus(o));d.put("partnerName",a==null?"":a.getDeliveryPartner().getName());d.put("assignedAt",a==null?null:a.getAssignedAt());d.put("partnerId",a==null?null:a.getDeliveryPartner().getId().toString());m.put("delivery",d);m.put("timeline",List.of(Map.of("status",adminStatus(o.getStatus()),"timestamp",o.getUpdatedAt())));m.put("allowedTransitions",allowedTransitions(o.getStatus()));m.put("canCancel",!EnumSet.of(OrderStatus.DELIVERED,OrderStatus.CANCELLED,OrderStatus.OUT_FOR_DELIVERY,OrderStatus.PICKED_UP).contains(o.getStatus()));return m;}
    private Map<String,Object> deliverySummary(CustomerOrder o){OrderAssignment a=assignments.findByOrderId(o.getId()).orElse(null);Map<String,Object>m=new LinkedHashMap<>();m.put("orderId",o.getId().toString());m.put("customerName",o.getCustomer().getName());m.put("customerPhone",o.getCustomer().getPhone());m.put("address",o.getAddressSnapshot());m.put("totalAmount",decimal(o.getTotalAmount()));m.put("currencyCode","INR");m.put("status",o.getStatus().name());m.put("paymentStatus",o.getPaymentStatus().name());m.put("assignedAt",a==null?null:a.getAssignedAt());m.put("createdAt",o.getCreatedAt());return m;}
    private Map<String,Object> deliveryDetails(CustomerOrder o,OrderAssignment a){List<String> actions=new ArrayList<>();switch(o.getStatus()){case DELIVERY_ASSIGNED,PARTNER_ASSIGNED->actions.add("ACCEPT");case PARTNER_ACCEPTED,PACKED->actions.add("PICKUP");case PICKED_UP->actions.add("OUT_FOR_DELIVERY");case OUT_FOR_DELIVERY->actions.add("COMPLETE");default->{} }Map<String,Object>m=new LinkedHashMap<>();m.put("orderId",o.getId().toString());m.put("customerName",o.getCustomer().getName());m.put("customerPhone",o.getCustomer().getPhone());m.put("address",o.getAddressSnapshot());m.put("totalAmount",o.getTotalAmount());m.put("currencyCode","INR");m.put("status",o.getStatus().name());m.put("paymentStatus",o.getPaymentStatus().name());m.put("items",o.getItems().stream().map(i->Map.of("productName",i.getProductName(),"quantity",i.getQuantity(),"unitPrice",decimal(i.getUnitPrice()),"lineTotal",decimal(i.getLineTotal()))).toList());m.put("assignedAt",a.getAssignedAt());m.put("createdAt",o.getCreatedAt());m.put("timeline",List.of(Map.of("status",o.getStatus().name(),"timestamp",o.getUpdatedAt())));m.put("allowedActions",actions);m.put("proofOfDeliveryRequired",false);m.put("proofOfDeliveryStatus","NOT_REQUIRED");m.put("proofOfDeliveryUrl","");return m;}
    private String assignmentStatus(CustomerOrder o){return assignments.findByOrderId(o.getId()).map(OrderAssignment::getStatus).orElse("UNASSIGNED");}
    private String adminStatus(OrderStatus s){return switch(s){case CREATED->"PENDING";case PAYMENT_PENDING->"PENDING";case PARTNER_SEARCHING->"CONFIRMED";case PARTNER_ASSIGNED->"ASSIGNED";case PARTNER_ACCEPTED->"ACCEPTED";case PICKING->"PREPARING";case PACKED->"READY";case DELIVERY_ASSIGNED->"ASSIGNED";default->s.name();};}
    private List<String> allowedTransitions(OrderStatus s){return switch(s){case CREATED->List.of("CONFIRMED","CANCELLED");case PAYMENT_PENDING->List.of("PENDING","CANCELLED");case PACKED->List.of("ASSIGNED","CANCELLED");case DELIVERY_ASSIGNED->List.of("PICKED_UP","CANCELLED");case PICKED_UP->List.of("OUT_FOR_DELIVERY");case OUT_FOR_DELIVERY->List.of("DELIVERED");default->List.of();};}
    private Map<String,Object> categoryDto(Category c){Map<String,Object>m=new LinkedHashMap<>();m.put("categoryId",c.getId().toString());m.put("name",c.getName());m.put("description",c.getDescription());m.put("imageUrl",c.getImageUrl());m.put("active",c.isActive());m.put("productCount",products.findAll().stream().filter(p->p.getCategory().getId().equals(c.getId())).count());m.put("sortOrder",c.getDisplayOrder());m.put("createdAt",null);m.put("updatedAt",null);m.put("allowedActions",List.of("EDIT",c.isActive()?"DEACTIVATE":"ACTIVATE"));return m;}
    private Map<String,Object> productSummary(Product p){return Map.ofEntries(Map.entry("productId",p.getId().toString()),Map.entry("name",p.getName()),Map.entry("categoryId",p.getCategory().getId().toString()),Map.entry("categoryName",p.getCategory().getName()),Map.entry("price",decimal(p.getMrp())),Map.entry("discountedPrice",decimal(p.getSellingPrice())),Map.entry("currencyCode","INR"),Map.entry("stock",p.getStockQuantity()),Map.entry("unit",p.getUnit()),Map.entry("status",p.isAvailability()?"ACTIVE":"INACTIVE"),Map.entry("availability",p.isAvailability()?"IN_STOCK":"OUT_OF_STOCK"),Map.entry("imageUrl",p.getImageUrl()==null?"":p.getImageUrl()));}
    private Map<String,Object> productDetails(Product p){Map<String,Object>m=new HashMap<>(productSummary(p));m.put("description",p.getDescription());m.put("discountPercent",decimal(p.getDiscountPercentage()));m.put("sku",p.getSku());m.put("createdAt",p.getCreatedAt());m.put("updatedAt",p.getUpdatedAt());m.put("allowedActions",List.of("EDIT",p.isAvailability()?"DEACTIVATE":"ACTIVATE"));return m;}
    private Map<String,Object> customerDto(Customer c){long count=orders.findAllByOrderByCreatedAtDesc().stream().filter(o->o.getCustomer().getId().equals(c.getId())).count();BigDecimal spent=orders.findAllByOrderByCreatedAtDesc().stream().filter(o->o.getCustomer().getId().equals(c.getId())&&o.getStatus()!=OrderStatus.CANCELLED).map(CustomerOrder::getTotalAmount).filter(Objects::nonNull).reduce(BigDecimal.ZERO,BigDecimal::add);Map<String,Object>m=new LinkedHashMap<>();m.put("customerId",c.getId().toString());m.put("name",c.getName());m.put("phone",c.getPhone());m.put("email",c.getEmail()==null?"":c.getEmail());m.put("profileImageUrl","");m.put("accountStatus",c.getStatus());m.put("registeredAt",c.getCreatedAt());m.put("lastActiveAt",c.getUpdatedAt());m.put("orderCount",count);m.put("totalSpent",spent.doubleValue());m.put("currencyCode","INR");m.put("defaultAddress","");m.put("allowedActions",List.of("ACTIVE".equals(c.getStatus())?"DEACTIVATE":"ACTIVATE","SUSPENDED".equals(c.getStatus())?"REACTIVATE":"SUSPEND"));return m;}
    private Map<String,Object> partnerSummary(DeliveryPartner p){long active=assignments.findByDeliveryPartnerIdOrderByAssignedAtDesc(p.getId()).stream().filter(a->a.getOrder().getStatus()!=OrderStatus.DELIVERED&&a.getOrder().getStatus()!=OrderStatus.CANCELLED).count();return Map.of("partnerId",p.getId().toString(),"name",p.getName(),"phone",p.getPhone(),"profileImageUrl","","accountStatus",p.isActive()?"ACTIVE":"INACTIVE","verificationStatus",p.getVerificationStatus(),"availability",p.isAvailable()?"ONLINE":"OFFLINE","workState",active>0?"BUSY":"AVAILABLE","activeDeliveries",active,"isAssignable",p.isActive()&&p.isAvailable()&&"VERIFIED".equals(p.getVerificationStatus()));}
    private Map<String,Object> partnerDetails(DeliveryPartner p){Map<String,Object>m=new HashMap<>(partnerSummary(p));List<OrderAssignment>a=assignments.findByDeliveryPartnerIdOrderByAssignedAtDesc(p.getId());m.put("email",p.getEmail()==null?"":p.getEmail());m.put("registeredAt",p.getCreatedAt());m.put("lastActiveAt",p.getLastActiveAt());m.put("vehicleType",p.getVehicleType());m.put("vehicleNumber",p.getVehicleNumber());m.put("licenseReference",p.getLicenseReference());m.put("statistics",Map.of("totalDeliveries",a.size(),"completedDeliveries",a.stream().filter(x->x.getOrder().getStatus()==OrderStatus.DELIVERED).count(),"cancelledDeliveries",a.stream().filter(x->x.getOrder().getStatus()==OrderStatus.CANCELLED).count(),"activeDeliveries",a.stream().filter(x->x.getOrder().getStatus()!=OrderStatus.DELIVERED&&x.getOrder().getStatus()!=OrderStatus.CANCELLED).count()));m.put("currentOrders",a.stream().filter(x->x.getOrder().getStatus()!=OrderStatus.DELIVERED&&x.getOrder().getStatus()!=OrderStatus.CANCELLED).limit(20).map(x->Map.of("orderId",x.getOrder().getId().toString(),"status",x.getOrder().getStatus().name(),"timestamp",x.getAssignedAt())).toList());m.put("recentHistory",a.stream().filter(x->x.getOrder().getStatus()==OrderStatus.DELIVERED||x.getOrder().getStatus()==OrderStatus.CANCELLED).limit(20).map(x->Map.of("orderId",x.getOrder().getId().toString(),"status",x.getOrder().getStatus().name(),"timestamp",x.getAssignedAt())).toList());m.put("allowedActions",List.of(p.isActive()?"DEACTIVATE":"ACTIVATE",p.getVerificationStatus().equals("VERIFIED")?"REJECT":"VERIFY"));return m;}
    private Map<String,Object> profileDto(DeliveryPartner p){Map<String,Object>m=new LinkedHashMap<>();m.put("id",p.getId());m.put("name",p.getName());m.put("phone",p.getPhone());m.put("email",p.getEmail()==null?"":p.getEmail());m.put("profileImageUrl","");m.put("verificationStatus",p.getVerificationStatus());m.put("accountStatus",p.isActive()?"ACTIVE":"INACTIVE");m.put("vehicleType",p.getVehicleType()==null?"":p.getVehicleType());m.put("vehicleNumber",p.getVehicleNumber()==null?"":p.getVehicleNumber());m.put("licenseReference",p.getLicenseReference()==null?"":p.getLicenseReference());m.put("registeredAt",p.getCreatedAt());m.put("lastActiveAt",p.getLastActiveAt());m.put("editableFields",List.of("name","email","vehicleType","vehicleNumber","licenseReference"));return m;}
    private String decimal(BigDecimal value){return value==null?null:value.setScale(2,java.math.RoundingMode.HALF_UP).toPlainString();}
    private <T> Map<String,Object> page(List<T> list,int page,int size,java.util.function.Function<T,Map<String,Object>> mapper){int safe=Math.max(1,size), pages=(int)Math.ceil(list.size()/(double)safe);int from=Math.min(Math.max(0,page)*safe,list.size()),to=Math.min(from+safe,list.size());List<Map<String,Object>> content=list.subList(from,to).stream().map(mapper).toList();return Map.of("content",content,"number",Math.max(0,page),"page",Math.max(0,page),"size",safe,"pageSize",safe,"totalPages",pages,"totalElements",(long)list.size(),"last",to>=list.size(),"hasNextPage",to<list.size());}
}
