package com.nexamart.backend.service;
import com.nexamart.backend.api.ApiModels.*;import com.nexamart.backend.config.AppProperties;import com.nexamart.backend.domain.*;import com.nexamart.backend.exception.ApiException;import com.nexamart.backend.repository.UserAccountRepository;import com.nexamart.backend.security.JwtService;import org.springframework.http.HttpStatus;import org.springframework.security.crypto.password.PasswordEncoder;import org.springframework.stereotype.Service;import java.time.Instant;
@Service public class AuthService{final UserAccountRepository users;final PasswordEncoder encoder;final JwtService jwt;final AppProperties props;final com.nexamart.backend.repository.DeliveryPartnerProfileRepository profiles;public AuthService(UserAccountRepository u,PasswordEncoder e,JwtService j,AppProperties p,com.nexamart.backend.repository.DeliveryPartnerProfileRepository pr){users=u;encoder=e;jwt=j;props=p;profiles=pr;}
 public LoginResponse login(LoginRequest r){UserAccount u=users.findByEmailIgnoreCase(r.identifier()).or(()->users.findByUsernameIgnoreCase(r.identifier())).orElseThrow(()->new ApiException(HttpStatus.UNAUTHORIZED,"Invalid login details. Please try again."));if(u.getStatus()!=AccountStatus.ACTIVE)throw new ApiException(HttpStatus.FORBIDDEN,"Account is not active.");if(!encoder.matches(r.password(),u.getPasswordHash()))throw new ApiException(HttpStatus.UNAUTHORIZED,"Invalid login details. Please try again.");u.setLastActiveAt(Instant.now());users.save(u);return tokens(u);}
 public LoginResponse register(RegisterRequest r){ return registerWithRole(r, Role.DELIVERY_PARTNER); }
 public LoginResponse registerCustomer(RegisterRequest r){ return registerWithRole(r, Role.CUSTOMER); }
 private LoginResponse registerWithRole(RegisterRequest r, Role role){if(!r.password().equals(r.confirmPassword()))throw new ApiException(HttpStatus.BAD_REQUEST,"Passwords do not match.");if(users.existsByEmailIgnoreCase(r.email()))throw new ApiException(HttpStatus.CONFLICT,"Email is already registered.");UserAccount u=new UserAccount();u.setName(r.name().trim());u.setEmail(r.email().trim().toLowerCase());u.setPhone(r.phone());u.setPasswordHash(encoder.encode(r.password()));u.setRole(role);u.setStatus(AccountStatus.ACTIVE);u=users.save(u);if(role==Role.DELIVERY_PARTNER){var profile=new com.nexamart.backend.domain.DeliveryPartnerProfile();profile.setUser(u);profiles.save(profile);}return tokens(u);}
 public LoginResponse refresh(RefreshRequest r){if(!jwt.validRefresh(r.refreshToken()))throw new ApiException(HttpStatus.UNAUTHORIZED,"Refresh token is invalid or expired.");var c=jwt.parse(r.refreshToken());UserAccount u=users.findById(((Number)c.get("uid")).longValue()).orElseThrow(()->new ApiException(HttpStatus.UNAUTHORIZED,"Account not found."));if(u.getStatus()!=AccountStatus.ACTIVE)throw new ApiException(HttpStatus.FORBIDDEN,"Account is not active.");return tokens(u);}
 public UserResponse user(UserAccount u){return new UserResponse(u.getId(),u.getName(),u.getPhone(),u.getEmail(),u.getRole().name());}
 private LoginResponse tokens(UserAccount u){return new LoginResponse(jwt.accessToken(u.getId(),u.getEmail()!=null?u.getEmail():u.getUsername(),u.getRole().name()),jwt.refreshToken(u.getId(),u.getEmail()!=null?u.getEmail():u.getUsername(),u.getRole().name()),user(u));}
 public void ensureAdmin(){users.findByUsernameIgnoreCase(props.getAdminUsername()).orElseGet(()->{UserAccount a=new UserAccount();a.setName(props.getAdminName());a.setUsername(props.getAdminUsername());a.setEmail(props.getAdminEmail());a.setPasswordHash(encoder.encode(props.getAdminPassword()));a.setRole(Role.ADMIN);a.setStatus(AccountStatus.ACTIVE);return users.save(a);});}
}
