package com.nexamart.backend.service;
import com.nexamart.backend.api.ApiModels.*;import com.nexamart.backend.domain.*;import com.nexamart.backend.exception.ApiException;import com.nexamart.backend.repository.*;import org.springframework.data.domain.*;import org.springframework.http.HttpStatus;import org.springframework.stereotype.Service;import java.math.BigDecimal;import java.time.Instant;import java.util.*;
@Service public class CatalogService{final CategoryRepository cats;final ProductRepository products;final MappingService map;public CatalogService(CategoryRepository c,ProductRepository p,MappingService m){cats=c;products=p;map=m;}
 public PageResponse<CategoryResponse> categories(int page,int size,String q,Boolean active){Page<Category> p=cats.findAll(PageRequest.of(Math.max(0,page),Math.min(Math.max(1,size),100),Sort.by("sortOrder").ascending().and(Sort.by("name").ascending())));List<CategoryResponse> list=p.getContent().stream().filter(c->active==null||c.isActive()).filter(c->q==null||c.getName().toLowerCase().contains(q.toLowerCase())).map(c->map.category(c,(int)products.search(null,null,c.getId(),Pageable.unpaged()).getTotalElements())).toList();return new PageResponse<>(list,p.getNumber(),p.getSize(),p.getTotalPages(),p.getTotalElements(),p.hasNext());}
 public PageResponse<ProductResponse> products(int page,int size,String q,Boolean active,Long categoryId){Page<Product> p=products.search(q,active,categoryId,PageRequest.of(Math.max(0,page),Math.min(Math.max(1,size),100),Sort.by("name")));return new PageResponse<>(p.getContent().stream().map(map::product).toList(),p.getNumber(),p.getSize(),p.getTotalPages(),p.getTotalElements(),p.hasNext());}
 public CategoryResponse categoryDetail(Long id){Category c=cats.findById(id).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Category not found."));int count=(int)products.search(null,null,id,Pageable.unpaged()).getTotalElements();return map.category(c,count);}
 public CategoryResponse createCategory(Map<String,Object> b){String name=String.valueOf(b.getOrDefault("name","")).trim();if(name.isBlank())throw new ApiException(HttpStatus.BAD_REQUEST,"Category name is required.");if(cats.findByNameIgnoreCase(name).isPresent())throw new ApiException(HttpStatus.CONFLICT,"Category already exists.");Category c=new Category();c.setName(name);c.setDescription((String)b.get("description"));c.setSortOrder(intVal(b.get("sortOrder"),0));return map.category(cats.save(c),0);}
 public CategoryResponse updateCategory(Long id,Map<String,Object>b){Category c=cats.findById(id).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Category not found."));if(b.containsKey("name"))c.setName(String.valueOf(b.get("name")).trim());if(b.containsKey("description"))c.setDescription((String)b.get("description"));if(b.containsKey("sortOrder"))c.setSortOrder(intVal(b.get("sortOrder"),c.getSortOrder()));c.touch();return map.category(cats.save(c),0);}
 public void categoryAction(Long id,ActionRequest r){Category c=cats.findById(id).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Category not found."));switch(r.action().toUpperCase()){case "ACTIVATE"->c.setActive(true);case "DEACTIVATE"->c.setActive(false);case "DELETE"->{if(products.search(null,null,id,Pageable.ofSize(1)).getTotalElements()>0)throw new ApiException(HttpStatus.CONFLICT,"Category has products. Deactivate it instead.");cats.delete(c);return;}default->throw new ApiException(HttpStatus.BAD_REQUEST,"Unsupported category action.");}c.touch();cats.save(c);}
 private int intVal(Object v,int d){try{return v==null?d:Integer.parseInt(v.toString());}catch(Exception e){return d;}}
 public ProductResponse createProduct(Map<String,Object>b){String name=String.valueOf(b.getOrDefault("name","")).trim();if(name.isBlank())throw new ApiException(HttpStatus.BAD_REQUEST,"Product name is required.");Long cid=Long.valueOf(String.valueOf(b.get("categoryId")));Category c=cats.findById(cid).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Category not found."));Product x=new Product();x.setName(name);x.setDescription((String)b.get("description"));x.setCategory(c);x.setPrice(new BigDecimal(String.valueOf(b.getOrDefault("price","0"))));x.setDiscount(new BigDecimal(String.valueOf(b.getOrDefault("discount","0"))));x.setSku((String)b.get("sku"));x.setUnit((String)b.get("unit"));x.setStock(intVal(b.get("stock"),0));x.setAvailable(Boolean.parseBoolean(String.valueOf(b.getOrDefault("available",true))));x.setImageUrl((String)b.get("imageUrl"));return map.product(products.save(x));}
 public ProductResponse updateProduct(Long id,Map<String,Object>b){Product x=products.findById(id).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Product not found."));if(b.containsKey("name"))x.setName(String.valueOf(b.get("name")));if(b.containsKey("description"))x.setDescription((String)b.get("description"));if(b.containsKey("categoryId"))x.setCategory(cats.findById(Long.valueOf(String.valueOf(b.get("categoryId")))).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Category not found.")));if(b.containsKey("price"))x.setPrice(new BigDecimal(String.valueOf(b.get("price"))));if(b.containsKey("discount"))x.setDiscount(new BigDecimal(String.valueOf(b.get("discount"))));if(b.containsKey("sku"))x.setSku((String)b.get("sku"));if(b.containsKey("unit"))x.setUnit((String)b.get("unit"));if(b.containsKey("stock"))x.setStock(intVal(b.get("stock"),x.getStock()));if(b.containsKey("available"))x.setAvailable(Boolean.parseBoolean(String.valueOf(b.get("available"))));if(b.containsKey("imageUrl"))x.setImageUrl((String)b.get("imageUrl"));x.touch();return map.product(products.save(x));}
 public void productAction(Long id,ActionRequest r){Product x=products.findById(id).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Product not found."));switch(r.action().toUpperCase()){case "ACTIVATE"->x.setAvailable(true);case "DEACTIVATE"->x.setAvailable(false);case "DELETE"->products.delete(x);default->throw new ApiException(HttpStatus.BAD_REQUEST,"Unsupported product action.");}products.save(x);}

 public ProductResponse productDetail(Long id){return map.product(products.findById(id).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Product not found.")));}
 public List<CategoryOption> categoryOptions(){return cats.findAll(Sort.by("sortOrder").ascending()).stream().filter(Category::isActive).map(c->new CategoryOption(c.getId().toString(),c.getName())).toList();}
 public record CategoryOption(String categoryId,String name){}

}
