package com.nexamart.backend.service;
import com.nexamart.backend.api.ApiModels.*;import com.nexamart.backend.domain.*;import com.nexamart.backend.exception.ApiException;import com.nexamart.backend.repository.*;import com.nexamart.backend.security.CurrentUser;import org.springframework.data.domain.*;import org.springframework.http.HttpStatus;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.math.*;import java.time.Instant;import java.util.*;
@Service public class CustomerService{final UserAccountRepository users;final ProductRepository products;final CategoryRepository cats;final OrderRepository orders;final OrderItemRepository items;final AddressRepository addresses;final NotificationRepository notes;final DeliveryPartnerProfileRepository profiles;final MappingService map;public CustomerService(UserAccountRepository u,ProductRepository p,CategoryRepository c,OrderRepository o,OrderItemRepository i,AddressRepository a,NotificationRepository n,DeliveryPartnerProfileRepository pr,MappingService m){users=u;products=p;cats=c;orders=o;items=i;addresses=a;notes=n;profiles=pr;map=m;}
 private UserAccount me(){return users.findById(CurrentUser.id()).orElseThrow(()->new ApiException(HttpStatus.UNAUTHORIZED,"Session expired."));}
 @Transactional public OrderResponse create(CreateOrderRequest r){UserAccount c=me();if(c.getStatus()!=AccountStatus.ACTIVE)throw new ApiException(HttpStatus.FORBIDDEN,"Account is not active.");Address a=new Address();a.setCustomer(c);a.setRecipientName(r.address().recipientName());a.setPhone(r.address().phone());a.setAddressLine(r.address().addressLine());a.setCity(r.address().city());a.setState(r.address().state());a.setPostalCode(r.address().postalCode());a.setLatitude(r.address().latitude());a.setLongitude(r.address().longitude());a.setDefaultAddress(r.address().defaultAddress());a=addresses.save(a);Order o=new Order();o.setCustomer(c);o.setDeliveryAddress(a);o.setPaymentMethod(r.paymentMethod()==null?PaymentMethod.COD:r.paymentMethod());if(o.getPaymentMethod()!=PaymentMethod.COD)throw new ApiException(HttpStatus.BAD_REQUEST,"Only Cash on Delivery is currently available.");o.setPaymentStatus(PaymentStatus.PENDING);o=orders.save(o);BigDecimal subtotal=BigDecimal.ZERO;for(var req:r.items()){Product p=products.findById(req.productId()).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Product not found: "+req.productId()));if(!p.isAvailable()||p.getStock()<req.quantity())throw new ApiException(HttpStatus.CONFLICT,"Product unavailable or insufficient stock: "+p.getName());BigDecimal line=p.getPrice().subtract(p.getDiscount().max(BigDecimal.ZERO)).multiply(BigDecimal.valueOf(req.quantity));OrderItem i=new OrderItem();i.setOrder(o);i.setProduct(p);i.setProductName(p.getName());i.setUnitPrice(p.getPrice().subtract(p.getDiscount().max(BigDecimal.ZERO)));i.setQuantity(req.quantity());i.setLineTotal(line);items.save(i);p.setStock(p.getStock()-req.quantity());products.save(p);subtotal=subtotal.add(line);}o.setSubtotal(subtotal);o.setDeliveryFee(subtotal.compareTo(new BigDecimal("500"))>=0?BigDecimal.ZERO:new BigDecimal("30.00"));o.setTotal(subtotal.add(o.getDeliveryFee()));o=orders.save(o); final Order savedOrder=o; profiles.findAll().stream().filter(DeliveryPartnerProfile::isAvailable).filter(x->x.getUser()!=null && x.getUser().getStatus()==AccountStatus.ACTIVE).forEach(x->{Notification n=new Notification();n.setUser(x.getUser());n.setTitle("New delivery order");n.setMessage("New order #"+savedOrder.getId()+" is available for delivery.");n.setType(NotificationType.ORDER_ASSIGNED);n.setOrderId(savedOrder.getId());notes.save(n);}); return response(o);}
 public PageResponse<OrderResponse> history(int page,int size){Page<Order> p=orders.findByCustomerId(me().getId(),PageRequest.of(page,size,Sort.by(Sort.Direction.DESC,"createdAt")));return new PageResponse<>(p.getContent().stream().map(this::response).toList(),p.getNumber(),p.getSize(),p.getTotalPages(),p.getTotalElements(),p.hasNext());}
 public OrderResponse detail(Long id){Order o=orders.findById(id).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Order not found."));if(!o.getCustomer().getId().equals(me().getId()))throw new ApiException(HttpStatus.FORBIDDEN,"Order is not yours.");return response(o);}
 private OrderResponse response(Order o){return map.order(o);}

}
