package com.nexamart.backend.service;
import com.nexamart.backend.api.ApiModels.*;import com.nexamart.backend.domain.*;import com.nexamart.backend.repository.OrderItemRepository;import org.springframework.stereotype.Service;import java.math.BigDecimal;import java.time.Instant;import java.util.*;
@Service public class MappingService{private final OrderItemRepository items;public MappingService(OrderItemRepository i){items=i;}public UserResponse user(UserAccount u){return u==null?null:new UserResponse(u.getId(),u.getName(),u.getPhone(),u.getEmail(),u.getRole().name());}
 public List<String> orderActions(Order o,boolean partner){List<String>a=new ArrayList<>();if(partner){if(o.getDeliveryPartner()!=null&&!o.getDeliveryPartner().getId().equals(com.nexamart.backend.security.CurrentUser.id()))return a;switch(o.getStatus()){case PENDING,ASSIGNED->a.add("ACCEPT");case ACCEPTED->a.add("PICKUP");case PICKED_UP->a.add("OUT_FOR_DELIVERY");case OUT_FOR_DELIVERY->a.add("COMPLETE");default->{}}}else{switch(o.getStatus()){case PENDING->a.add("CONFIRMED");case CONFIRMED->a.add("PREPARING");case PREPARING->a.add("READY");default->{}}if(o.getDeliveryPartner()==null&&o.getStatus()!=OrderStatus.CANCELLED&&o.getStatus()!=OrderStatus.DELIVERED)a.add("ASSIGN");if(o.getStatus()!=OrderStatus.CANCELLED&&o.getStatus()!=OrderStatus.DELIVERED)a.add("CANCEL");}return a;}
 public String address(Order o){if(o.getDeliveryAddress()==null)return null;return String.join(", ",Arrays.asList(o.getDeliveryAddress().getAddressLine(),o.getDeliveryAddress().getCity(),o.getDeliveryAddress().getState(),o.getDeliveryAddress().getPostalCode()).stream().filter(Objects::nonNull).filter(x->!x.isBlank()).toList());}
 public List<OrderItemResponse> itemResponses(Order o){return items.findByOrderId(o.getId()).stream().map(i->new OrderItemResponse(i.getId(),i.getProduct().getId(),i.getProductName(),i.getUnitPrice(),i.getQuantity(),i.getLineTotal())).toList();}
 public OrderResponse order(Order o){boolean partner=org.springframework.security.core.context.SecurityContextHolder.getContext().getAuthentication()!=null&&org.springframework.security.core.context.SecurityContextHolder.getContext().getAuthentication().getAuthorities().stream().anyMatch(a->a.getAuthority().equals("ROLE_DELIVERY_PARTNER"));List<OrderItemResponse> ir=itemResponses(o);List<OrderTimelineDto> tl=new ArrayList<>();tl.add(new OrderTimelineDto("PENDING",o.getCreatedAt().toString()));if(o.getAcceptedAt()!=null)tl.add(new OrderTimelineDto("ACCEPTED",o.getAcceptedAt().toString()));if(o.getPickedUpAt()!=null)tl.add(new OrderTimelineDto("PICKED_UP",o.getPickedUpAt().toString()));if(o.getOutForDeliveryAt()!=null)tl.add(new OrderTimelineDto("OUT_FOR_DELIVERY",o.getOutForDeliveryAt().toString()));if(o.getDeliveredAt()!=null)tl.add(new OrderTimelineDto("DELIVERED",o.getDeliveredAt().toString()));PaymentInfoDto pay=new PaymentInfoDto(o.getPaymentMethod().name(),o.getPaymentStatus().name(),null);BigDecimal discount=ir.stream().map(i->i.unitPrice().multiply(BigDecimal.valueOf(i.quantity())).subtract(i.lineTotal())).reduce(BigDecimal.ZERO,BigDecimal::add);OrderTotalsDto totals=new OrderTotalsDto(o.getSubtotal().toString(),o.getDeliveryFee().toString(),discount.max(BigDecimal.ZERO).toString(),"0.00",o.getTotal().toString(),o.getCurrencyCode());DeliveryInfoDto di=new DeliveryInfoDto(o.getStatus().name(),o.getDeliveryPartner()==null?null:o.getDeliveryPartner().getName(),o.getAcceptedAt()==null?null:o.getAcceptedAt().toString(),o.getDeliveryPartner()==null?null:o.getDeliveryPartner().getId().toString());String assignedAt=o.getAcceptedAt()==null?null:o.getAcceptedAt().toString();return new OrderResponse(o.getId().toString(),o.getCustomer().getName(),o.getCustomer().getPhone(),address(o),o.getTotal().toString(),o.getCurrencyCode(),o.getStatus().name(),o.getPaymentStatus().name(),assignedAt,o.getCreatedAt().toString(),ir.size(),o.getStatus().name(),user(o.getCustomer()),ir,pay,totals,di,tl,orderActions(o,false),o.getStatus()!=OrderStatus.DELIVERED&&o.getStatus()!=OrderStatus.CANCELLED,user(o.getDeliveryPartner()),orderActions(o,partner),false,null,null);}
 public DeliveryOrderSummary deliverySummary(Order o){return new DeliveryOrderSummary(o.getId().toString(),o.getCustomer().getName(),o.getCustomer().getPhone(),address(o),o.getTotal().toString(),o.getCurrencyCode(),o.getStatus().name(),o.getPaymentStatus().name(),o.getAcceptedAt()==null?null:o.getAcceptedAt().toString(),o.getCreatedAt().toString(),o.getTotal().toString());}
 public ProductResponse product(Product p){BigDecimal discounted=p.getPrice().subtract(p.getDiscount()==null?BigDecimal.ZERO:p.getDiscount()).max(BigDecimal.ZERO);String status=p.isAvailable()?"ACTIVE":"INACTIVE";return new ProductResponse(p.getId().toString(),p.getName(),p.getDescription(),p.getCategory().getId().toString(),p.getCategory().getName(),p.getPrice().toString(),discounted.toString(),p.getDiscount()==null?"0":p.getDiscount().toString(),"INR",p.getStock(),p.getSku(),p.getUnit(),status,p.isAvailable()?"AVAILABLE":"UNAVAILABLE",p.getImageUrl(),p.getCreatedAt(),p.getUpdatedAt(),p.isAvailable()?List.of("EDIT","DEACTIVATE"):List.of("EDIT","ACTIVATE"));}
 public CategoryResponse category(Category c,int count){return new CategoryResponse(c.getId().toString(),c.getName(),c.getDescription(),c.getImageUrl(),c.isActive(),count,c.getSortOrder(),c.getCreatedAt(),c.getUpdatedAt(),c.isActive()?List.of("EDIT","DEACTIVATE"):List.of("EDIT","ACTIVATE","DELETE"));}
}
